export const GET_PLAYER_STATS_PENDING = 'GET_PLAYER_STATS_PENDING';
export const GET_PLAYER_STATS_SUCCESS = 'GET_PLAYER_STATS_SUCCESS';
export const GET_PLAYER_STATS_FAILED = 'GET_PLAYER_STATS_FAILED';
export const ACTION_PENDING = 'ACTION_PENDING';
export const ACTION_SUCCESS = 'ACTION_SUCCESS';
export const ACTION_FAILED = 'ACTION_FAILED';
